### ISSUE TITLE
What happens when adding contrast in gradient

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#149]

**Comment by ilia3101** [comment]
If you adjust contrast in it before exposure it goes wrong white balance

**Comment by ilia3101** [comment]
also the contrast doesn't seem very good compared to the normal contrast slider. Is it doing contrast before exposure or what?

**Comment by ilia3101** [comment]
could the curves be added to gradient instead?

**Comment by masc4ii** [comment]
>If you adjust contrast in it before exposure it goes wrong white balance

Really? Can't reproduce. What exactly are you doing and in which way?

>also the contrast doesn't seem very good compared to the normal contrast slider. Is it doing contrast before exposure or what?

Both contrast sliders do exactly the same. Contrast is identical to your highlights/shadows sliders, but combined (Contrast = Highlights-Shadows) and applied directly to the picture (no blurred copy). So it is applied at the same step as exposure (to not loose data / to not clip). Whitebalance matrix should be one and the same (no copy existing) for both layers. 

In principle all parameters could be applied to the gradient layer too, but this means doubling all the code for that. (Don't like my implementation much here.) 

Using curves instead of contrast slider will have this side effect: applying more contrast will work, applying less contrast will lead to grey flat pictures because of clipped data. Contrast slider as it is should be way better for that.

**Comment by ilia3101** [comment]
> Really? Can't reproduce. What exactly are you doing and in which way?

Ok that was me being stupid, I had launched 1.3, and it seems you fixed it since. I am sorry.

> Both contrast sliders do exactly the same - code is identical.

I understand that, but in the exposure + contrast step, in which order is it done?

**Comment by masc4ii** [comment]
>I understand that, but in the exposure + contrast step, in which order is it done?

It is done at once in one equation.

**Comment by masc4ii** [comment]
Here it is done:

```
...
/* Gradient variables and part 1 */
        uint16_t pixg[3];
        if( processing->gradient_enable && gmpix[0] != 0 &&
          ( ( processing->gradient_exposure_stops < -0.01 || processing->gradient_exposure_stops > 0.01 )
         || ( processing->gradient_contrast       < -0.01 || processing->gradient_contrast       > 0.01 ) ) )
        {
            /* do the same for gradient as for the pic itself, but before the values are overwritten */
            /* white balance & exposure */
            int32_t pix0g = (pmg[0][pix[0]] /* + pmg[1][pix[1]] + pmg[2][pix[2]] */) * expo_correction * expo_correction_gradient;
            int32_t pix1g = (/* pmg[3][pix[0]] + */ pmg[4][pix[1]] /* + pmg[5][pix[2]] */) * expo_correction * expo_correction_gradient;
            int32_t pix2g = (/* pmg[6][pix[0]] + pmg[7][pix[1]] */ + pmg[8][pix[2]]) * expo_correction * expo_correction_gradient;
            int32_t tmp1g = (/* pmg[3][pix[0]] + */ pmg[4][pix[1]] /* + pmg[5][pix[2]] */);
...
```

**Comment by ilia3101** [comment]
Thanks I see it is the same as normal.

**Comment by ilia3101** [comment]
I have realised what the problem is - I was doing it on a bright area (sky), so contrast was pushing it upwards mostly. But there is still something strange going on when it clips in the gradient, I need to investigate a bit more.

**Comment by masc4ii** [comment]
Could you show what you mean?

**Comment by ilia3101** [comment]
Ok I'll find it

**Comment by masc4ii** [comment]
Do we still have this issue?

**Comment by masc4ii** [comment]
Feel free to reopen if you get the problem again!
