### ISSUE TITLE
AVFoundation h.265 export

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#156]
I just remembered how the AVFoundation library has h265... maybe we could compile a version on a new macOS machine with that enabled? - can there be a macro like IF MACOS VERSION > 10.11 or something?

I remembver @masc4ii  commented it out due to not compiling on old macs.

I think we could a macOS download for new one and the older one?

Also seems like dark mode would be supported this way

**Comment by masc4ii** [comment]
Could you have a try? Commited... but I am on 10.9 here, so I don't see what happens.

**Comment by ilia3101** [comment]
Thanks, but I have lost my wireless mouse so my iMac is useless, can't test today :cry:

 Will be able to soon hopefully. Maybe @dannephoto can try?

**Comment by dannephoto** [comment]
On vacay atm but will try and see if I can get some time to look into this.

**Comment by dannephoto** [comment]
h.265 working nicely on 10.14!
`Compressor Name                 : Lavc57.89.100 libx265`

Just tested, short export- 
Nice, nice!

**Comment by dannephoto** [comment]
7 second clip. 897kb! Crazy good compression:
https://bitbucket.org/Dannephoto/magic-lantern/downloads/h265.mov

Also:
https://www.magiclantern.fm/forum/index.php?topic=20025.msg213777#msg213777

**Comment by masc4ii** [comment]
The "new" h.265 added here is AVFoundation, the ffmpeg h.265 presets were added longtime ago. AVFoundation works on MAC only, and you need XCode for 10.13+. That's why I can't test what Ilia and I implemented. Selected it with the options comboBox. 

The ffmpeg setting used is `...-c:v libx265 -preset medium -crf 24...`

**Comment by bouncyball-git** [comment]
Do not know about Apple but ffmpeg uses open source x265 code and it is far the best encoder for h265 at the moment.

**Comment by dannephoto** [comment]
Aha, good, can tweak and test. I also tested h264 encoder and it seems we have more headroom here as well. When set correctly this encoder yields as good if not better end viewing results as prores.

**Comment by dannephoto** [comment]
Ok, realize I was testing ffmpeg h265 preset along with ffmpeg h264 preset above. The refined settings are valid(and imo needed) to get high quality output.

About avfoundation h265 codec I can´t seem to find it so I don´t think it was compiled or I am doing something wrong I work in Mojave 10.14 here. First. Where do I find "comboBox" :)?

**Comment by masc4ii** [comment]
It should look like this:
![Bildschirmfoto 2019-03-22 um 18 06 10](https://user-images.githubusercontent.com/30245296/54840459-68193580-4ccd-11e9-8135-a64cedb95b45.png)
But you only see it, if you use a Apple SDK since 10.13. In compiler output you should find, which SDK is used. Here, I see this:
`.../usr/local/opt/llvm/bin/clang++ -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk...`
--> to old.

**Comment by dannephoto** [comment]
I suspected this. Will look into it but every time I fiddle around with sdk versions it's like starting a nuclear melt down...

**Comment by masc4ii** [comment]
Tried out your ffmpeg setting... h265 shows the first two images only... I think my laptop is too old for such games 😄

**Comment by DeafEyeJedi** [comment]
Tried playing back Danne’s H.265 on 10.14 which wouldn’t play back because QT isn’t supported. Hmm?

**Comment by masc4ii** [comment]
Hehe... yepp... Quicktime doesn't support this, same problem here. VLC is able to playback (if machine is fast enough).

**Comment by dannephoto** [comment]
What setting was applied crf 14?
I think crf 18 is usable but after this shadows will break too much for both codecs @masc.

**Comment by masc4ii** [comment]
Yepp. Okay. h265 @crf18 works. h264 @crf14 works too. Will commit.

**Comment by dannephoto** [comment]
Hm, getting this when compiling:
```
Project WARNING: Qt has only been tested with version 10.13 of the platform SDK, you're using 10.14.1.
Project WARNING: This is an unsupported configuration. You may experience build issues, and by using
Project WARNING: the 10.14.1 SDK you are opting in to new features that Qt has not been prepared for.
Project WARNING: Please downgrade the SDK you use to build your app to version 10.13, or configure
Project WARNING: with CONFIG+=sdk_no_version_check when running qmake to silence this warning.
```

ANd seeing this:
`/usr/local/opt/llvm/bin/clang -c -pipe -fopenmp -O2  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk`

Well, good luck on downgrading, sigh...

**Comment by masc4ii** [comment]
Ups... no fun. 😢  Sorry. But good to know.

**Comment by dannephoto** [comment]
I tested by copying from  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/ into /Library/Developer/CommandLineTools/SDKs/ and got 10.13 in there and it comiles without errors now. But no extra h265 setting in the roll down menu, hmmmm

**Comment by masc4ii** [comment]
Strange. Unfortunately I can't test myself. But I thought that `#if MAC_OS_X_VERSION_MIN_REQUIRED >= 101300` works for this.

**Comment by dannephoto** [comment]
Seems I can comment out:
```
#if MAC_OS_X_VERSION_MIN_REQUIRED >= 101300
        if( index == CODEC_H265 )
        {
            ui->comboBoxOption->addItem( QString( "Apple AVFoundation" ) );
        }
#endif
```

Into:
`            ui->comboBoxOption->addItem( QString( "Apple AVFoundation" ) );`
And it gets me the AV foundation in the combobox. It exports only to mkv but seems to work. Unclear...
So somthing not wirking with #if #endif?

**Comment by masc4ii** [comment]
I don't know if you get what you think you get. This line exists very often in other code files too. Maybe you get an ffmpeg file. MKV don't sounds like AVFoundation.

**Comment by dannephoto** [comment]
yeah, most likely ffmpeg file. Seems to be same size when comparing to ffmpeg so it´s not getting the av foundation stuff...

**Comment by bouncyball-git** [comment]
Hey guys!

x265 constant rate lower than 18 is real overkill. This produces huge files with very small almost unnoticeable improvement in quality (bitrate is higher and decoder straggles on low and CPUs). I really needed to have this option for quick preview clips or for sharing purpose so 18 is the lowest for that matter. Otherwise I would export prores.

@masc: it we really need to go lower than 18, let's make option for selecting the quality.

**Comment by masc4ii** [comment]
It is at 18 now. If lower I can't playback the files... 😄

**Comment by bouncyball-git** [comment]
I think the text field to insert directly rate factor will be the easiest solution. Saving the value into program settings. With default 20.

**Comment by dannephoto** [comment]
Well both h264 and h265 are possible end formats meaning they could end up being used for high quality viewing purposes or as mentioned by bouncyball for fast previewing(low quality). Both should be available if possible.

**Comment by dannephoto** [comment]
I think there can be two settings for each code:
websized
highqual
Or something similar. No need for manual bitrate selection imo.

**Comment by masc4ii** [comment]
What settings number for websized?

**Comment by bouncyball-git** [comment]
> Or something similar. No need for manual bitrate selection imo.

This is not a bitrate, it's rate (can be interpreted as quality) factor and IS extremely straight forward. 

Range is between 0-51. 
0 - lossless, 51 - worse quality. The sane range is 18-28. 

I think the dumbest user can use this approach without issues :grin:

**Comment by dannephoto** [comment]
Well, 24(was that default before) Is crushing darks but is usable for webviewing and possibly uploading to youtube. Personally I can stick to the high quality sizes since they are still very small in sizes. But I think 24 is good number if we now can choose between high and low res.

**Comment by masc4ii** [comment]
Imo a slider is overkill... I think it is too difficult for what we get. It is just used for those codecs, otherwise we should hide the slider. Each parameter must be transferred from one class to another. The parameter has to be used in pipe output. ... Normally the user wants maximum quality or preview quality. I think if we add 2 quality options ("high"=10/18 & "medium"=24) this should be enough and we can realize it with just the option combobox, we already have. Is that okay for you?

**Comment by dannephoto** [comment]
Completely agree

**Comment by masc4ii** [comment]
https://github.com/ilia3101/MLV-App/commit/77eaf0721b5fede40e8ca0152b66302fd251b405
Please test.

**Comment by bouncyball-git** [comment]
Great! Like it. 18 and 24. :+1:

**Comment by dannephoto** [comment]
Yes, good! Difference is noticeable.
