### ISSUE TITLE
What is the main cause of slow performance?

### ISSUE THREAD

**Issue by ilia3101** [ilia3101/MLV-App#181]
What takes up the most time, encoding with ffmpeg or the processing?

And how is the video creation done? process frame, then write it to video file, repeat... or is frame processing and video writing in parallel?

And why don't we process multiple frames at a time anymore? We could also try multiple clips in parallel.

**Comment by masc4ii** [comment]
First: I don't think it is sooo slow. CPU is mostly only some % below 100% here when rendering... more is not possible. Adobe is way slower and Resolve has more or less the same speed (when not owning a monster GPU, like me).

How is it done:
We render frame by frame. When a frame is ready we send it by pipe to ffmpeg. When ffmpeg is ready, next frame is rendered. ffmeg is multithreaded. MLVApp processing is partly (but mostly) multithreaded. Both in parallel makes no sense, because both apps would fight against each other for their CPU power. But MLVApp always must be a very little faster, else ffmpeg has nothing to do.

Where we can get faster ( = what is still single threaded) :
- DualISO
- Recursive biliteral filtering (Shadows/Highlights/Clarity/Denoiser)
- ?! Forgot...

When we decided for the current concept, because it was more efficient and easier to realize. Cons for multiple frames at a time concept:
- pink frames when multiple threads read the same file (This was never solved. I had to single access until I removed this concept.)
- pipeline should be single threaded completely
- we need a large buffer for sorting frames before sending in right order to ffmpeg
- ffmpeg fights against MLVApp, instead of working hand in hand

**Comment by masc4ii** [comment]
For RBF filter, see their repos. There are ways to make it 10x faster! The only problem: they use 8bit per channel. I changed the easiest code to 16bit per channel. I had no success with the faster versions. Maybe you're better than me!
https://github.com/Fig1024/OP_RBF
This would speed up so much!!!

**Comment by ilia3101** [comment]
Thanks! very helpful answer.

> Adobe is way slower and Resolve has more or less the same speed (when not owning a monster GPU, like me).

Glad to hear Adobe is slower (what I was hopinh)

> pink frames when multiple threads read the same file (This was never solved. I had to single access until I removed this concept.)

Maybe by having a few mlv objects we could have solved this, I think without caching they use only a tiny amount of ram.

>  We render frame by frame. When a frame is ready we send it by pipe to ffmpeg. When ffmpeg is ready, next frame is rendered. ffmeg is multithreaded. MLVApp processing is partly (but mostly) multithreaded. Both in parallel makes no sense, because both apps would fight against each other for their CPU power. But MLVApp always must be a very little faster, else ffmpeg has nothing to do.

Ok this makes sense, assuming both ffmpeg and mlv app use multiple cores to 100%, which I guess ffmpeg does (?) and MLV App also tries.

**Comment by ilia3101** [comment]
> For RBF filter, see their repos. There are ways to make it 10x faster! The only problem: they use 8bit per channel. I changed the easiest code to 16bit per channel. I had no success with the faster versions. Maybe you're better than me!
> https://github.com/Fig1024/OP_RBF
> This would speed up so much!!!

So anoying that everyone makes image algorithms in 8 bit :((

I will have a read of the code and see if it makes any sense. Even at current speed it's impressive.

I think avx2 could be nice in mlv app processing.

**Comment by masc4ii** [comment]
> Ok this makes sense, assuming both ffmpeg and mlv app use multiple cores to 100%, which I guess ffmpeg does (?) and MLV App also tries.

Maybe not exactly 100, but close to it.

> So anoying that everyone makes image algorithms in 8 bit :(( 
> I will have a read of the code and see if it makes any sense. Even at current speed it's impressive.
> I think avx2 could be nice in mlv app processing.

Yes... anoying. But hey... the for the algorithms I changed in past, it was mostly a simple uint8_t to uint16_t and 255 to 65535 replacement. 😄 

Yes, have a read! Maybe you get the idea for making it better! avx2 is nice - but it is very hard to read and understand the code. At least I don't understand much of it.

**Comment by ilia3101** [comment]
> Yes, have a read! Maybe you get the idea for making it better! avx2 is nice - but it is very hard to read and understand the code. At least I don't understand much of it.

I have a tiny understanding of using sse, I hope it'll be a case of swapping int8 instructions for 16 bit (and processing 2x less pixels at a time, hopefully not difficult to figure this out).

Looks not too diffcult at first sight. What would be a simple way to swap the sse version in to MLV App?

I don't want to use the AVX version because it's only supported since intel 2011.

**Comment by masc4ii** [comment]
Yepp, this is all I understood from this as well. But then I had no more success. For trying out, see the files without "wrapper" in "MLV_App/src/processing/rbfilter" . Those are the files from that repos. It should be possible to exchange it easily. The calls are in the wrapper files, to make our C code able to run the C++ code.

Ah okay... sse should be better than. My computers are older than 2011. :-D 
Raspberry Pi? Crazy cool! :-D And I hope for a simplified Android version one day. (Qt should be able to use and compile the code for Android).

**Comment by ilia3101** [comment]
> For trying out, see the files without "wrapper" in "MLV_App/src/processing/rbfilter" . Those are the files from that repos. It should be possible to exchange it easily. The calls are in the wrapper files, to make our C code able to run the C++ code.

Understood, thanks.

> And I hope for a simplified Android version one day. (Qt should be able to use and compile the code for Android).

That would be really amazing. I have wanted that too. Didn't know Qt was also on android.
