### ISSUE TITLE
Help please rookie questions...

### ISSUE THREAD

**Issue by pctech33** [ilia3101/MLV-App#204]
I would like to convert the MLV files to cinemadng preserving the way it was shot on the canon 5 d with the cinestyle profile and without any alterations from the MLV app.

How do I do that? Do I disable raw correction, creative adjustment and what else?
What gamma shall I keep? Any other settings I should disable? Tonemapping?

Again my scope is to preserve that flat profile as I make adjustments to premiere pro afterward.

I appreciate any help!!!

**Comment by masc4ii** [comment]
If you decide to record RAW, you decide to not use picture styles or flat profiles out of the camera. Using profiles will bring you processed picture data, but RAW is unprocessed picture data. 

So if you want to use picture styles, disable RAW recording in your camera. But there is absolutely no reason for a flat profile instead of RAW, because RAW has so much more information. You just need a program what is able to interpret this data.

Exporting CinemaDNG will bring also RAW picture data without any profile. Just RAW corrections are applied in MLVApp, but nothing else. Using CinemaDNG, it is 100% Premiere, what brings you the colors you see.

**Comment by pctech33** [comment]
Thank you! I am shooting raw with a flat profile. My concern was that converting MLV files to cinemadng via the MLV app, would apply some processing. I wanted to disable any possible processing that is applied by the MLV app so that I can keep the raw and flat profile intact (no alterations whatsoever).

As such, I disable "raw correction" in the MLV app and also "creative adjustment" but was not sure if I should disable other settings like gamma and tonemapping.

Thanks again! Appreciate it.

**Comment by masc4ii** [comment]
RAW Correction is no processing - you can correct e.g. bad pixels with that. All your color information stays the same.

RAW is not flat or something else... it is just RAW. If you use Premiere, it is the job of Premiere to "make it flat". The profile chosen in your cam is not applied to RAW footage.

**Comment by pctech33** [comment]
Thank you! Appreciate it.
    On Thursday, April 9, 2020, 08:34:34 AM EDT, masc4ii <notifications@github.com> wrote:  
 
 


RAW Correction is no processing - you can correct e.g. bad pixels with that. All your color information stays the same.

RAW is not flat or something else... it is just RAW. If you use Premiere, it is the job of Premiere to "make it flat". The profile chosen in your cam is not applied to RAW footage.

**Comment by pctech33** [comment]
Thanks I appreciate it!

**Comment by bouncyball-git** [comment]
Hm... Raw with flat profile... cool ;)
