### ISSUE TITLE
Export clip metadata separately in a data sheet/pdf or have it in the ProRes/cDNG files

### ISSUE THREAD

**Issue by Joonas12334** [ilia3101/MLV-App#212]
Would make life a little easier as usually when exporting I'm only getting the time when was the clip exported. Thank you for the excellent app!

**Comment by masc4ii** [comment]
Thanks for writing your wish. cDNGs should already hold all metadata. ProRes files can't hold metadata. I'll think about creating a PDF or XLSX for the session with all metadata, of that helps. A table with all metadata from all clips is already implemented...

**Comment by vastunghia** [comment]
Maybe a plain CSV file would be probably even more quick to implement and would anyway hit the target? Would be super useful in many cases.

**Comment by masc4ii** [comment]
Please test. 9198fa1d88e1a2e6191f202b468812aa4afb5a02

**Comment by vastunghia** [comment]
Whoah that was fast! Thanks a lot masc, I tested and I confirm successful export of CSV file. All data is there. Wonderful!

It would be nice if separator was comma instead of tab, but that would require all text strings not to include any comma -- or to be in quotation marks. Like:

`<tab>1/50 s,  181 deg,  20117 µs<tab>`

could become

`,"1/50 s,  181 deg,  20117 µs",`

This would make the exported CSV compliant with standards IMO. But these are details, and the exported CSV is perfectly usable. So thanks, once again.

**Comment by vastunghia** [comment]
By the way, there is another enhancement that would make this one really useful. That is, upon opening of a list of MLV files, MLV App should be populating rows in the table for all those clips that have a MAPP file already available -- not only for the last clip.

Otherwise, one needs to manually double click on each and every clip to have the table fully populated. Or, choose "Create All MAPP files now", even though all MAPP files already exist.

Would this make any sense? Shall I open a new feature request?

**Comment by masc4ii** [comment]
Comma separation is no good idea, because for some locations a value can be 1.2 and in some others 1,2. So reading csv would fail in some countries. That's why I've chosen the tab, which is not used in any value.

The other thing is a feature: there is MLV fast import and standard import. 1st is fast, 2nd is very slow. For large projects it would need a long time to read all values from all MLVs on opening a session. So we created the fast import, which just reads the very first block of the MLV -> reduced metadate available only. "Create All MAPP files now" fully opens all MLV files - so this way you get all the metadata out of all clips.

**Comment by vastunghia** [comment]
Yes I know very well, unfortunately I live in a place where value is 1,2 instead of 1.2 (which is universal scientific standard AFAIK) -- that's why one of the first things when I install a new OS is changing this setting system-wide :-) I still think that 1. separator = comma, 2. decimal separator = point and 3. all field values in brackets like this

`"Text string 1","Text string 2","This text string has a number like 1.2 or 1,2 in it, but who cares as long as it is in brackets as this will be interpreted as a text string and not as number","1.2","1,2","Last two values are once again text strings and not numbers, so no problem as well"`

would be more portable than tab (I think that Excel, for instance, will not automatically recognize tab-separated files in any location, neither in the 1,2 nor in the 1.2 ones). But hey, this is more philosophy than anything else, so let there be tab!

Re: last point, I thought that MAPP files contained metadata and that MAPP files were read upon opening of MLV files. I understand your explanation though, very clear, thank you. Would it be possible to have a "Slow Import" option as well? I store my MLV files on a super-fast internal NVME PCIe drive (almost 3000 MB/s read speed!) and I have the feeling that, in my case, fast import makes little to no sense. Or could you tell me how to tweak the code in order to switch from fast to standard import mode? At least I could give it a try.

Thanks!

**Comment by masc4ii** [comment]
I added fast open as option. I hope it has no side effects. Please test! 😄

**Comment by vastunghia** [comment]
C'est genial. Brilliant, works like a charm. This is it, thank you!
