### ISSUE TITLE
Features for still photography editing

### ISSUE THREAD

**Issue by orfeas-a** [ilia3101/MLV-App#263]
I've recently used the app to edit stills with great results and I am trying to find a way to make the workflow easier, mainly by adding an option to rotate vertical frames and a JPG batch export.

**Rotation**
I looked at the algorithm used for the upside down mode in the source and found that it is the algorithm for rotating a matrix 180 degrees, adjusted for the MLV backend. I remember seeing on a post that it wouldn't be possible to do it any other way because of how it's currently implemented, so I searched for the algorithm for a 90 degree rotation but I couldn't implement it because I don't have enough knowledge on the MLV structure or matrix math. Is it worth giving it a try?

**Batch export**
I haven't worked on that yet because I just batch export the photos as TIFF and then compress them to JPG using other software. I was just thinking of trying to add the option of not creating a new folder for every single TIFF as the feature is intended for sequences. As I understand it wouldn't be possible to add a JPG export like the current frame export as all batch exports use ffmpeg?

Any info/suggestion is appreciated!

**Comment by masc4ii** [comment]
Rotation of 90° in MLVApp is possible, if we rewrite the complete processing and backend. The entire app is not made to change from native resolution - in the old days nobody thought about that. So unfortunatelly no real option right now, and also the reason why it doesn't already exist. 180° was easy, because all structures and metadata stay untouched.

Exporting a JPG sequence via ffmpeg is possible. Until now people wanted max quality when exporting sequnces (and encode to video using other software), so there was no usecase yet. If you are on macOS you could also write an post export script, which converts TIFF to JPEG via ffmpeg, copy to any folder you like, and clean all temp files. That should be the easiest way, without touching any line of app code.
