### ISSUE TITLE
Logic of color processing pipeline of MLV App

### ISSUE THREAD

**Issue by bouncyball-git** [ilia3101/MLV-App#83]
Hey guys!

@ilia3101 

When I'm looking at the code in processing dir and trying to comprehend the whole pipeline of the color processing, honestly I'm a bit lost there, because: 
1) I'm not very good at theory and also 
2) there in the code are lots of experimental and _even_not_used_ functions, constants, conversions, etc.

So I'm really interesting in the theory of this pipeline and the roadmap you are thinking of. I want to ask you to explain whole Idea and pipeline you are after and document it here (this will be like MLV App color processing Wiki here). I'm sure @masc4ii also will be glad to have this documented guide for better understanding this field and even help you with some stuff if needed.

My proposal is to start from: raw-rgb -> wb(cam matrix) -> illuminant adaptation -> destination color space (maybe I'm wrong here in this sequence). So please explain this pipeline (shortly but human understandably :), maybe with some references to the theory sources you used)

Thank you in advance
bb

**Comment by masc4ii** [comment]
In principle: no bad idea to document all this. But I think after some weeks this thread is not nice to read. Another idea: github has a wiki: https://github.com/ilia3101/MLV-App/wiki
Could that be better for documenting?

**Comment by bouncyball-git** [comment]
Good! It just a matter of @ilia3101 desire and his spare time :)

**Comment by ilia3101** [comment]
I can try and explain it. It would be helpful even for me as sometimes I don't remember what going on.

**Comment by ilia3101** [comment]
I think the real difficulty for you understanding it is how badly written it is, the code is a bit of a mess (I always get lost when doing improvements to it). The processing logic behind it is not very good, and there is a few more improvements coming in the white balance branch.

**Comment by bouncyball-git** [comment]
It does not matter how bad or good code is written, can this be outlined somehow to represent some kind of manual/doc? @masc4ii as I see you already comprehend a lot of it. Can you help in that regard? MLV App processing is a real white spot on the map for me ;)

**Comment by masc4ii** [comment]
Yes, that would be important. But I don't know yet how to write that down. Something interactive would be good where you could click through... but the solutions I know are not free.

**Comment by ilia3101** [comment]
Almost everything in processing is done through 65535-long lookup tables for more speed than using actual calculations (and quite badly organized in my opinion, all the arrays[65536] in the processing object are look up tables. I find it confusing to read).

This use of 16 bit integers only causes a huge amount of difficulties with not clipping things, and is why developing new features like highlights and shadows got difficult (also why I did it wrong - did not want to clip stuff - more on this later). However all the processing features I created never ever clipped anything (well, almost, information could be lost when no tonemapping then exposure increase followed by saturation reduction), but it's basically the same result as if it was done in floats... just more difficult to program new features.

The intention of these methods was to make it run quick, and I remember at the very start (back in early 2017), I could get one frame processed in 40ms on one thread. Not sure if it was ever that fast by the time it got a GUI.


## Processing a frame

(I have missed out some stuff that has been recently added by masc, because I might describe it wrong)
#### start
`applyProcessingObject()`

1. shadows and highlights... (just remembered there is actually a big problem in the implmentation)
Done on debayered raw image before black/white level correction and exposure (this is the problem)

`applyProcessingObject()` calls `apply_processing_object()` split in to threads

2. Black and white level correction (look up table)
3. Matrix (does white balance, no camera matrix stuff) - there are a few new variables and things in this area of the code that I'm not sure what they do I think some are by masc
4. Gamma through lookup table, gamma look up table also has exposure and tonemap function applied in it all in one go (so highlight data won't get clipped before tonemapping)
5. Highlight reconstruction done same time as the matrix
6. Saturation using some weird algorithm I came up with that seemed quick, also using strange lookup tables
7. Contrast look up table
8. if enabled, conversion to ycbcr through some lookup tables
9. Sharpening, on all channels if rgb, or on just Y channel if ycbcr
10. if chroma blur enabled and in ycbcr, cb and cr channels are blurred
11. convert back to rgb from ycbcr
12. LUT applied
13. my stupid slow neural network filter applied



That's the best I could do with my current understanding :smiley_cat:

**Comment by ilia3101** [comment]
Sorry i only noticed this ages later

**Comment by masc4ii** [comment]
3. yes, there are some new variables to realize contrast and clarity. This work exactly like highlights/shadows but:
- contrast: combines shadows/highlights with no blurred picture
- clarity: combines contrast and shadows/highlights

5. For dual iso clips, the "normal" highlight reconstruction does not work, because the "highestgreen" is lower than expected - and can be different in each frame. I implemented a special dual iso highlight reconstruction version: the first thing is to find this value by searching for the highest peak in green channel. That does not always work well (it would work perfectly as single thread) and is very slow :(

6a) vibrance: works exaclty like saturation, but calculates RGB to (H)S(V) (S channel only) to be able to set saturation in dependency to saturation already beeing there. The less saturation there was before, the more saturation will be after applying vibrance.

**Comment by bouncyball-git** [comment]
> Not sure if this exactly what you wanted or if it's helpful, but ask anything else you want @bouncyball-git if I haven't included it in there

Thank you very much, there are no questions so far.

**Comment by masc4ii** [comment]
I created a wiki page, which we can use as small documentation. Here in this thread the day would come soon, nobody understands what we did... so you can write your understanding of what we did on this page, or create more pages...:
https://github.com/ilia3101/MLV-App/wiki

**Comment by masc4ii** [comment]
I tried to write a little user manual. See wiki page:
https://github.com/ilia3101/MLV-App/wiki

Please review and correct it, if you like! For pattern noise I have no idea what it does... 😄

**Comment by bouncyball-git** [comment]
Fantastic wiki!
