### ISSUE TITLE
v0.16

### ISSUE THREAD

**Issue by masc4ii** [ilia3101/MLV-App#88]
Hej guys,
do you still plan features to be realized soon? Since 53 days there was no new version. Now new is:
- Shadows & Highlights is now multithreaded
- Audio for AVFoundation export (macOS only)
- Update checker
- Post export scripting on macOS including first two scripts (thx @dannephoto)
- DualISO: Bugfix for 12bit and less
- Bugfix for file names with ä, ö, ü, ß, ...

Would that be enough for v0.16?

**Comment by dannephoto** [comment]
I think these features deserves an upgrade. I use Mlv App as per always for previewing and often use it as a tool for cutting MLV, HDR footage and so on.

**Comment by masc4ii** [comment]
@dannephoto : this could be the macOS solution for https://github.com/ilia3101/MLV-App/issues/64 ?!

**Comment by dannephoto** [comment]
I´d say it´s a solution for 5D mark III users working with proxy h.264 files since it can match MLV clip exactly regarding audio and proxy video. Adding audio from an external recorder will be problematic. Unlike the magic lantern proxy files which has a few black frames which goes into video the very second the MLV starts recording making it possible to find the exact sync point automatically an external audio file will have to be manually synched in post, so different story.

**Comment by bouncyball-git** [comment]
Never used that proxy stuff myself. Since mlv_lite/mlv-audio tandem is working nicely.

**Comment by bouncyball-git** [comment]
OT: I wonder if there is possibility for CF controller overclocking...

**Comment by masc4ii** [comment]
v0.16 is out for OSX. @bouncyball-git : could you please build 64bit Windows version?

**Comment by masc4ii** [comment]
32bit Windows is uploaded too.

**Comment by bouncyball-git** [comment]
Uploaded :)
